<a href="https://colab.research.google.com/github/0792211827/Zindi-Microsoft-Learn-Location-Mention-Recognition-Challenge/blob/main/LMR_NO1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import spacy

In [2]:
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl (587.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 1.1 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.10/dist-packages (from en-core-web-lg==3.7.1) (3.7.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.9.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (71.0.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.3 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.23.3)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (13.8.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.16.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.2)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
nlp = spacy.load("en_core_web_lg")
nlp

In [6]:
import pandas as pd
# Load the training data
train = pd.read_csv('/content/Train_1 (1).csv')
test = pd.read_csv('/content/Test (2).csv')

# Display the first few rows to confirm data loading
train.head()

,tweet_id,text,location
0,ID_1001136212718088192,NaN,EllicottCity
1,ID_1001136696589631488,"Flash floods struck a Maryland city on Sunday,...",Maryland
2,ID_1001136950345109504,State of emergency declared for Maryland flood...,Maryland
3,ID_1001137334056833024,Other parts of Maryland also saw significant d...,Baltimore Maryland
4,ID_1001138374923579392,"Catastrophic Flooding Slams Ellicott City, Mar...",Ellicott City Maryland

In [13]:
test.head()

                 tweet_id                                               text
0  ID_1001154804658286592  What is happening to the infrastructure in New...
1  ID_1001155505459486720  SOLDER MISSING IN FLOOD.. PRAY FOR EDDISON HER...
2  ID_1001155756371136512  RT @TIME: Police searching for missing person ...
3  ID_1001159445194399744  Flash Flood Tears Through Maryland Town For Se...
4  ID_1001164907587538944  Ellicott City #FLOODING Pictures: Maryland Gov...

In [7]:
train.isnull().sum()

tweet_id        0
text        56624
location    29612
dtype: int64

In [8]:
test.isnull().sum()

tweet_id    0
text        0
dtype: int64

In [9]:
train = train.dropna()

In [10]:
train.apply(lambda x:len(x.unique()))

tweet_id    11849
text        11849
location     3448
dtype: int64

In [11]:
import re

In [14]:
# Removing Digits
train['text'] = train['text'].apply(lambda d: re.sub(r'\d','', d) if isinstance(d, str) else d)
test['text'] = test['text'].apply(lambda d: re.sub(r'\d','', d) if isinstance(d, str) else d)

In [15]:
#removing commas
train['text'] = train['text'].apply(lambda v: re.sub(',', '', v) if isinstance(v, str) else v)
test['text'] = test['text'].apply(lambda v: re.sub(',', '', v) if isinstance(v, str) else v)

In [16]:
#a function to remove emojis
def remove_emoji(text):
    if not isinstance(text, str):
        return text
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # Emoticons
        "\U0001F300-\U0001F5FF"  # Symbols & Pictographs
        "\U0001F680-\U0001F6FF"  # Transport & Map Symbols
        "\U0001F700-\U0001F77F"  # Alchemical Symbols
        "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U0001FA00-\U0001FA6F"  # Chess Symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U00002702-\U000027B0"  # Dingbats
        "\U000024C2-\U0001F251"  # Enclosed Characters
        "]+", flags=re.UNICODE)

    return emoji_pattern.sub(r'', text)

train['text'] = train['text'].apply(remove_emoji)
test['text'] = test['text'].apply(remove_emoji)

In [17]:
#remove HTML tags
def remove_html(text):
    if not isinstance(text, str):
        return text
    html_pattern = re.compile(r'<.*?>')
    return html_pattern.sub(r'', text)
train['text'] = train['text'].apply(remove_html)
test['text'] = test['text'].apply(remove_html)

In [18]:
# remove URLs
def remove_URL(text):
    if not isinstance(text, str):
        return text
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

train['text'] = train['text'].apply(remove_URL)
test['text'] = test['text'].apply(remove_URL)

In [21]:
from string import punctuation

In [22]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [24]:
import string
punctuation = string.punctuation + "’‘"
# Apply the function to remove all punctuation characters, ignoring non-string values
train['text'] = train['text'].apply(lambda doc: "".join([x for x in doc if x not in punctuation]) if isinstance(doc, str) else doc)
test['text'] = test['text'].apply(lambda doc: "".join([x for x in doc if x not in punctuation]) if isinstance(doc, str) else doc)

In [25]:
train.sample(50)

,tweet_id,text,location
27181,ID_1111742103023947776,RT SoutheastFFAOH To help the victims of the N...,Nebraska
68296,ID_912385206333722624,Puerto Rico Holds Its Breath Over HurricaneBat...,Puerto Rico
44538,ID_797895840077475840,RT MomentsAU The extent of damage caused by a ...,Kaikoura New Zealand
37447,ID_1176766879203037184,Mirpur AJK Earthquake Update via NDMA SEP ...,AJK Jatlan Mirpur
37707,ID_1177140334096257024,Around people have died over are injured af...,Mirpur Pakistan
37990,ID_721727201574580224,RT PSYCHICTWINS Biggest quake since Dead Aft...,Ecuadors
37463,ID_1176775614256148480,News earthquake Nineyearold killed in Lahore r...,Lahore
26932,ID_1111438787706421248,RT beinlibertarian Pssst Hey you Help us out i...,Nebraska
30448,ID_1167745000085577728,Hurricane Dorian forecast to reach FL as a Cat...,FL Florida kissimmee orlando
5806,ID_1032168504424726528,Nasscomm Foundation Kerala Flood Relief Reha...,Kerala
4226,ID_1031083099088674816,Glimpse of KeralaFloodRelief efforts onground ...,Chengannur Pathanamthita
38519,ID_721911659971932160,Quake in Ecuador death toll rises to watch de...,Ecuador
27144,ID_1111716551009419264,Thank you to Tracy Dices financial literacy cl...,Nebraska
67201,ID_911991923442962432,RT DannyWildeOk IDF Israel Defense Forces sold...,Israel Mexico
42553,ID_783424998580957184,RT NevieLuna billclinton I heard realDonaldTru...,Haiti
26667,ID_1111165777594499072,Back to Mozambique and Zimbabwe today with Int...,Mozambique South African Zimbabwe
11400,ID_1039887775695347712,RT PaulMiles JUST IN RedCross in Kentucky is s...,Kentucky
60244,ID_908158498122473472,St Thomas resident on Irma aftermath We really...,St. Thomas
27567,ID_1112530689155584000,CourtneyJohnsTV Dine and Donate April rd at a...,Nebraska
781,ID_1021750834449797120,Greek wildfires devastate resort area near Ath...,Athens
29862,ID_1167606676448522240,You can the eye of Hurricane Dorian STATE OF E...,FLORIDA
22143,ID_1065675089381916672,California Fire Relief Efforts Harrison Ford P...,California Malibu
20742,ID_1064693647126355968,JuddLegum Walmart Another thing about WalMart ...,California
17169,ID_1061443151427260416,RT BMalmet The worst fires ever in California ...,California
9336,ID_1036818628161617920,people have died due to Rat Fever in the past...,Kerala
43578,ID_783869285001207808,Hurricane Matthew Photos of the Destruction in...,Haiti
36323,ID_1176486624777179136,RT dawncom dead more than injured as magnitu...,Pakistan
62741,ID_908851618266959872,LITechNews people still missing in Sri Lanka ...,Sri Lanka
39914,ID_729452348762808320,Buildings destroyed by a wildfire in Fort McMu...,Alberta Fort McMurray
988,ID_1021827037131169792,abarhk Greece A big fire near Athens Over peo...,Athens Greece
66022,ID_910808789242318848,Hurricane Maria destroys homes causes flooding...,Puerto Rico
27747,ID_1112806436424253440,Its time to rebuild Chimanimani surrounding a...,Chimanimani
1734,ID_1023395190051164160,Funerals for the victims of Greeces lethal wil...,Mati
64552,ID_910560404476108800,RT BBCBreaking More than people have been kil...,Mexico
18420,ID_1062382512259952640,California WILDFIRE Location Maps Update Malib...,California Malibu
36644,ID_1176506598929391616,Emergency has been declared in Mirpur Azad Kas...,Azad Kashmir Mirpur
26216,ID_1110846260125282304,An RAF AM Atlas has delivered tonnes of lifes...,Malawi Mozambique UK Zimbabwe
36382,ID_1176490747652182016,Chairman National Disaster Management Authorit...,Ajk Islamabad Jatlan Mirpur Pakistan
66585,ID_911715509447487488,RT JohnHenryStyle Retweet if you think Amazon ...,Puerto Rico
66949,ID_911871108072247296,PHOTOS Rescuers Tirelessly Search For Earthqua...,Mexico City
56265,ID_905756526245269504,RT ScottTaylorTV Hurricane Irma death toll ris...,New Yorks
44397,ID_797871490788036608,We have had big damage here just km north of s...,kapiti
21043,ID_1064944086409392128,CampFireDonorKeltie Cole FB PostI am located i...,Santa Clarita
43468,ID_783819969171628032,people in haiti have already died and hundred...,haiti
18008,ID_1062104152182972416,RT VOANews California Wildfires Rage Death Tol...,California
66915,ID_911835135355564032,RT EW Gael García Bernal and Diego Luna start ...,Mexico
3118,ID_1030772658542194688,Urgent Requirement for KeralaFloods Sanitary P...,Kerala Trivandrum
38094,ID_721751838589108224,RT cruzrojaecuador Earthquake Ecuador Our volu...,Ecuador
70670,ID_913788767181340672,Former Island runner and coach says Hurricane ...,Puerto Rico
40326,ID_730450114465107968,NUPGE and its Components donate close to K for...,Alberta

In [29]:
train['text'].iloc[0]

'Flash floods struck a Maryland city on Sunday washing out streets and tossing cars like bath toys'

In [30]:
train['location'].iloc[0]

'Maryland'

In [31]:
# Initialize an empty list to store the training data
training_data = []

# Process each row in the DataFrame
for index, row in train.iterrows():
    temp_dict = {}

    # Ensure the cleaned_text is a string
    text = row['text'] if isinstance(row['text'], str) else ''
    temp_dict['text'] = text
    temp_dict['locations'] = []

    # Extract the location from the location column
    location = row['location']

    # Ensure the location is a string
    if isinstance(location, str):
        # Find the start and end positions of the location in the text
        start = text.find(location)
        end = start + len(location)

        # If location is found in the text
        if start != -1:
            temp_dict['locations'].append((start, end, 'LOCATION'))

    # Add the processed example to the training data
    training_data.append(temp_dict)

# Print the first entry in the training data to verify
print(training_data[0])

{'text': 'Flash floods struck a Maryland city on Sunday washing out streets and tossing cars like bath toys', 'locations': [(22, 30, 'LOCATION')]}

In [32]:
training_data[0]['locations']

[(22, 30, 'LOCATION')]

In [33]:
training_data[0]['text'][22:30]

'Maryland'

In [34]:
import pandas as pd
import re

# Initialize an empty list to store the training data
training_data = []

# Process only the first 10 rows in the DataFrame
for index, row in train.head(10).iterrows():
    temp_dict = {}

    # Ensure the cleaned_text is a string
    text = row['text'] if isinstance(row['text'], str) else ''
    temp_dict['text'] = text
    temp_dict['locations'] = []

    # Extract the location from the location column
    location = row['location'] if isinstance(row['location'], str) else ''

    # Use regular expression to find the location in the text if location is not empty
    if location:
        pattern = re.compile(re.escape(location), re.IGNORECASE)
        match = pattern.search(text)

        # If location is found in the text
        if match:
            start = match.start()
            end = match.end()
            temp_dict['locations'].append((start, end, 'LOCATION'))

    # Add the processed example to the training data
    training_data.append(temp_dict)

# Print the first 10 entries in the training data
for i in range(10):
    print(f"Entry {i}: {training_data[i]}")

Entry 0: {'text': 'Flash floods struck a Maryland city on Sunday washing out streets and tossing cars like bath toys', 'locations': [(22, 30, 'LOCATION')]}
Entry 1: {'text': 'State of emergency declared for Maryland flooding  via YouTube', 'locations': [(32, 40, 'LOCATION')]}
Entry 2: {'text': 'Other parts of Maryland also saw significant damage from Sundays storms including this Baltimore city neighborhood Dundalk and Catonsville Rain totals spanned from  to  inches across Maryland  ECFlood', 'locations': []}
Entry 3: {'text': 'Catastrophic Flooding Slams Ellicott City Maryland Water Rescues Reported  The Weather Channel  via GoogleNews', 'locations': [(28, 50, 'LOCATION')]}
Entry 4: {'text': 'WATCH  missing after flash FLOODING devastates Ellicott City Maryland  GPWX', 'locations': [(47, 69, 'LOCATION')]}
Entry 5: {'text': 'Watch Live Aerials of damage after historic flash flooding in Ellicott City Maryland', 'locations': [(62, 84, 'LOCATION')]}
Entry 6: {'text': 'One person is reported missing as a state of emergency is declared amid flash floods in Maryland kristendahlgren reports', 'locations': [(88, 96, 'LOCATION')]}
Entry 7: {'text': 'Monday May   Morning Report National Guardsman missing after monstrous floods sink Maryland town Trump visits Arlington after critics slam appalling Memorial Day tweet Via nypost', 'locations': []}
Entry 8: {'text': 'One man is still missing after flash flooding tore down historic Main Street in Ellicott City Maryland over the weekend', 'locations': [(80, 102, 'LOCATION')]}
Entry 9: {'text': 'RT KCCINews State of emergency declared in Maryland after heavy rain causes flooding', 'locations': [(43, 51, 'LOCATION')]}

In [35]:
# Initialize an empty list to store the training data
training_data = []

# Process only the first 10 rows in the DataFrame
for index, row in train.head(10).iterrows():
    temp_dict = {}

    # Ensure the cleaned_text is a string
    text = row['text'] if isinstance(row['text'], str) else ''
    temp_dict['text'] = text
    temp_dict['locations'] = []

    # Split the location column if it contains multiple locations
    locations = row['location'].split() if isinstance(row['location'], str) else []

    # Use regular expression to find each location in the text
    for location in locations:
        pattern = re.compile(re.escape(location), re.IGNORECASE)
        match = pattern.search(text)

        # If location is found in the text
        if match:
            start = match.start()
            end = match.end()
            temp_dict['locations'].append((start, end, 'LOCATION'))

    # Add the processed example to the training data
    training_data.append(temp_dict)

# Print the first 10 entries in the training data
for i in range(10):
    print(f"Entry {i}: {training_data[i]}")

Entry 0: {'text': 'Flash floods struck a Maryland city on Sunday washing out streets and tossing cars like bath toys', 'locations': [(22, 30, 'LOCATION')]}
Entry 1: {'text': 'State of emergency declared for Maryland flooding  via YouTube', 'locations': [(32, 40, 'LOCATION')]}
Entry 2: {'text': 'Other parts of Maryland also saw significant damage from Sundays storms including this Baltimore city neighborhood Dundalk and Catonsville Rain totals spanned from  to  inches across Maryland  ECFlood', 'locations': [(87, 96, 'LOCATION'), (15, 23, 'LOCATION')]}
Entry 3: {'text': 'Catastrophic Flooding Slams Ellicott City Maryland Water Rescues Reported  The Weather Channel  via GoogleNews', 'locations': [(28, 36, 'LOCATION'), (37, 41, 'LOCATION'), (42, 50, 'LOCATION')]}
Entry 4: {'text': 'WATCH  missing after flash FLOODING devastates Ellicott City Maryland  GPWX', 'locations': [(47, 55, 'LOCATION'), (56, 60, 'LOCATION'), (61, 69, 'LOCATION')]}
Entry 5: {'text': 'Watch Live Aerials of damage after historic flash flooding in Ellicott City Maryland', 'locations': [(62, 70, 'LOCATION'), (71, 75, 'LOCATION'), (76, 84, 'LOCATION')]}
Entry 6: {'text': 'One person is reported missing as a state of emergency is declared amid flash floods in Maryland kristendahlgren reports', 'locations': [(88, 96, 'LOCATION')]}
Entry 7: {'text': 'Monday May   Morning Report National Guardsman missing after monstrous floods sink Maryland town Trump visits Arlington after critics slam appalling Memorial Day tweet Via nypost', 'locations': [(110, 119, 'LOCATION'), (83, 91, 'LOCATION')]}
Entry 8: {'text': 'One man is still missing after flash flooding tore down historic Main Street in Ellicott City Maryland over the weekend', 'locations': [(80, 88, 'LOCATION'), (89, 93, 'LOCATION'), (94, 102, 'LOCATION')]}
Entry 9: {'text': 'RT KCCINews State of emergency declared in Maryland after heavy rain causes flooding', 'locations': [(43, 51, 'LOCATION')]}

In [36]:
training_data[8]['locations']

[(80, 88, 'LOCATION'), (89, 93, 'LOCATION'), (94, 102, 'LOCATION')]

In [39]:
slices = [training_data[8]['text'][start:end] for start, end in [(80, 88), (89, 93), (94, 102)]]

# Print the slices
print(slices)

['Ellicott', 'City', 'Maryland']

In [40]:
# Initialize an empty list to store the extracted locations for each row
extracted_locations = []

# Process all rows in the DataFrame
for index, row in train.iterrows():
     # Ensure the cleaned_text is a string
    text = row['text'] if isinstance(row['text'], str) else ''
    temp_dict['text'] = text
    temp_dict['locations'] = []

    # Initialize an empty list to store locations for the current row
    row_locations = []

    # Split the location column into individual locations if applicable
    locations = row['location'].split() if isinstance(row['location'], str) else []

    # Use regular expressions to find each location in the text
    for location in locations:
        pattern = re.compile(re.escape(location), re.IGNORECASE)
        match = pattern.search(text)

        # If a location is found, store the start and end positions
        if match:
            start = match.start()
            end = match.end()
            row_locations.append((start, end, 'LOCATION'))

    # Append the extracted locations for the current row to the list
    extracted_locations.append(row_locations)

# Create a new column 'extracted_locations' in the DataFrame
train['extracted_locations'] = extracted_locations

# Print the first few rows to verify
train[['text', 'location', 'extracted_locations']].head()

,text,location,extracted_locations
1,Flash floods struck a Maryland city on Sunday ...,Maryland,"[(22, 30, LOCATION)]"
2,State of emergency declared for Maryland flood...,Maryland,"[(32, 40, LOCATION)]"
3,Other parts of Maryland also saw significant d...,Baltimore Maryland,"[(87, 96, LOCATION), (15, 23, LOCATION)]"
4,Catastrophic Flooding Slams Ellicott City Mary...,Ellicott City Maryland,"[(28, 36, LOCATION), (37, 41, LOCATION), (42, ..."
5,WATCH missing after flash FLOODING devastates...,Ellicott City Maryland,"[(47, 55, LOCATION), (56, 60, LOCATION), (61, ..."

In [41]:
import spacy
from spacy.tokens import DocBin
from tqdm import tqdm

# Load a new blank spaCy model for English
nlp = spacy.blank("en")

# Initialize DocBin for storing processed documents
doc_bin = DocBin()

In [42]:
from tqdm import tqdm
from spacy.util import filter_spans

# Use the train DataFrame directly as the training data
training_data = train  # Ensure you're using the DataFrame with the 'extracted_locations' column

for training_example in tqdm(training_data.itertuples(), total=len(training_data)):
    text = training_example.text  # Use the 'text' column from the DataFrame
    labels = training_example.extracted_locations  # Use the 'extracted_locations' column

    # Create a doc object from the text
    doc = nlp.make_doc(text)
    ents = []

    # Add entities to the doc
    for start, end, label in labels:
        span = doc.char_span(start, end, label=label, alignment_mode="contract")
        if span is None:
            print(f"Skipping entity: {(start, end, label)}")
        else:
            ents.append(span)

    # Filter out overlapping spans
    filtered_ents = filter_spans(ents)
    doc.ents = filtered_ents

    # Add the doc to the DocBin
    doc_bin.add(doc)

# Save the processed data to a file
doc_bin.to_disk("train.spacy")

  5%|▍         | 549/11849 [00:00<00:06, 1689.19it/s]

Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (58, 66, 'LOCATION')
Skipping entity: (150, 158, 'LOCATION')
Skipping entity: (46, 50, 'LOCATION')
Skipping entity: (167, 171, 'LOCATION')
Skipping entity: (37, 45, 'LOCATION')
Skipping entity: (45, 49, 'LOCATION')
Skipping entity: (146, 150, 'LOCATION')
Skipping entity: (121, 127, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (23, 29, 'LOCATION')
Skipping entity: (75, 81, 'LOCATION')
Skipping entity: (220, 226, 'LOCATION')
Skipping entity: (164, 172, 'LOCATION')
Skipping entity: (158, 164, 'LOCATION')
Skipping entity: (45, 54, 'LOCATION')
Skipping entity: (39, 45, 'LOCATION')
Skipping entity: (173, 179, 'LOCATION')
Skipping entity: (22, 28, 'LOCATION')
Skipping entity: (103, 109, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')
Skipping entity: (54, 56, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (4, 10, 'LOCATION')
Skipping entity: (41, 47, 'LOCATION')
Skipping entity: (181, 187, 'LOCATION')
Skipping entity: (69, 75, 'LOCATION')
Skipping entity: (159, 165, 'LOCATION')
Skipping entity: (18, 24, 'LOCATION')
Skipping entity: (248, 254, 'LOCATION')
Skipping entity: (59, 65, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')

  8%|▊         | 902/11849 [00:00<00:06, 1634.98it/s]

Skipping entity: (55, 57, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (81, 87, 'LOCATION')
Skipping entity: (71, 77, 'LOCATION')
Skipping entity: (20, 27, 'LOCATION')
Skipping entity: (32, 38, 'LOCATION')
Skipping entity: (97, 103, 'LOCATION')
Skipping entity: (75, 81, 'LOCATION')
Skipping entity: (244, 250, 'LOCATION')
Skipping entity: (20, 26, 'LOCATION')
Skipping entity: (213, 219, 'LOCATION')
Skipping entity: (201, 207, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (74, 80, 'LOCATION')
Skipping entity: (81, 87, 'LOCATION')
Skipping entity: (14, 18, 'LOCATION')
Skipping entity: (60, 66, 'LOCATION')
Skipping entity: (51, 57, 'LOCATION')
Skipping entity: (56, 62, 'LOCATION')
Skipping entity: (245, 251, 'LOCATION')
Skipping entity: (43, 49, 'LOCATION')
Skipping entity: (32, 38, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')
Skipping entity: (189, 195, 'LOCATION')
Skipping entity: (200, 206, 'LOCATION')
Skipping entity: (78, 84, 'LOCATION')
Skipping entity: (56, 62, 'LOCATION')
Skipping entity: (28, 34, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (110, 116, 'LOCATION')
Skipping entity: (5, 7, 'LOCATION')
Skipping entity: (9, 15, 'LOCATION')
Skipping entity: (211, 217, 'LOCATION')

  9%|▉         | 1067/11849 [00:00<00:06, 1549.88it/s]

Skipping entity: (40, 46, 'LOCATION')
Skipping entity: (46, 52, 'LOCATION')
Skipping entity: (78, 84, 'LOCATION')
Skipping entity: (55, 62, 'LOCATION')
Skipping entity: (98, 104, 'LOCATION')
Skipping entity: (102, 108, 'LOCATION')
Skipping entity: (32, 41, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (74, 80, 'LOCATION')
Skipping entity: (176, 182, 'LOCATION')
Skipping entity: (71, 77, 'LOCATION')
Skipping entity: (63, 69, 'LOCATION')
Skipping entity: (85, 91, 'LOCATION')
Skipping entity: (47, 53, 'LOCATION')
Skipping entity: (199, 205, 'LOCATION')
Skipping entity: (199, 205, 'LOCATION')
Skipping entity: (160, 169, 'LOCATION')
Skipping entity: (89, 95, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (126, 132, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (23, 29, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (100, 106, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (49, 55, 'LOCATION')
Skipping entity: (8, 14, 'LOCATION')
Skipping entity: (35, 41, 'LOCATION')
Skipping entity: (18, 24, 'LOCATION')
Skipping entity: (209, 214, 'LOCATION')
Skipping entity: (214, 216, 'LOCATION')
Skipping entity: (57, 59, 'LOCATION')
Skipping entity: (159, 166, 'LOCATION')
Skipping entity: (23, 29, 'LOCATION')
Skipping entity: (12, 18, 'LOCATION')
Skipping entity: (47, 53, 'LOCATION')
Skipping entity: (83, 89, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (84, 93, 'LOCATION')
Skipping entity: (27, 33, 'LOCATION')
Skipping entity: (84, 90, 'LOCATION')
Skipping entity: (69, 75, 'LOCATION')
Skipping entity: (4, 10, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (231, 237, 'LOCATION')

 13%|█▎        | 1526/11849 [00:00<00:07, 1460.03it/s]

Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (10, 16, 'LOCATION')
Skipping entity: (80, 86, 'LOCATION')
Skipping entity: (211, 216, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (101, 107, 'LOCATION')
Skipping entity: (34, 40, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (17, 22, 'LOCATION')
Skipping entity: (191, 196, 'LOCATION')
Skipping entity: (50, 55, 'LOCATION')
Skipping entity: (44, 50, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (47, 53, 'LOCATION')
Skipping entity: (63, 69, 'LOCATION')
Skipping entity: (30, 35, 'LOCATION')
Skipping entity: (24, 30, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (101, 107, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (13, 19, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (11, 17, 'LOCATION')
Skipping entity: (35, 41, 'LOCATION')
Skipping entity: (31, 37, 'LOCATION')
Skipping entity: (34, 40, 'LOCATION')
Skipping entity: (23, 29, 'LOCATION')
Skipping entity: (154, 159, 'LOCATION')
Skipping entity: (116, 122, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (35, 41, 'LOCATION')
Skipping entity: (42, 48, 'LOCATION')
Skipping entity: (5, 11, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (27, 32, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (112, 121, 'LOCATION')
Skipping entity: (127, 133, 'LOCATION')
Skipping entity: (71, 77, 'LOCATION')
Skipping entity: (9, 15, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (12, 18, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (27, 33, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (173, 179, 'LOCATION')
Skipping entity: (14, 22, 'LOCATION')
Skipping entity: (68, 74, 'LOCATION')
Skipping entity: (14, 20, 'LOCATION')
Skipping entity: (182, 190, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')

 16%|█▌        | 1843/11849 [00:01<00:06, 1515.66it/s]

Skipping entity: (70, 76, 'LOCATION')
Skipping entity: (92, 97, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (14, 19, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (16, 20, 'LOCATION')
Skipping entity: (25, 31, 'LOCATION')
Skipping entity: (25, 31, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (63, 69, 'LOCATION')
Skipping entity: (16, 22, 'LOCATION')
Skipping entity: (16, 21, 'LOCATION')
Skipping entity: (177, 183, 'LOCATION')
Skipping entity: (33, 39, 'LOCATION')
Skipping entity: (70, 76, 'LOCATION')
Skipping entity: (8, 14, 'LOCATION')
Skipping entity: (145, 152, 'LOCATION')
Skipping entity: (152, 158, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (49, 55, 'LOCATION')
Skipping entity: (49, 55, 'LOCATION')
Skipping entity: (14, 20, 'LOCATION')
Skipping entity: (67, 73, 'LOCATION')
Skipping entity: (17, 23, 'LOCATION')
Skipping entity: (18, 28, 'LOCATION')
Skipping entity: (212, 223, 'LOCATION')
Skipping entity: (99, 105, 'LOCATION')
Skipping entity: (39, 45, 'LOCATION')
Skipping entity: (39, 45, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (102, 110, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (51, 56, 'LOCATION')
Skipping entity: (56, 66, 'LOCATION')
Skipping entity: (51, 56, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')
Skipping entity: (184, 190, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (44, 50, 'LOCATION')
Skipping entity: (204, 209, 'LOCATION')
Skipping entity: (53, 55, 'LOCATION')
Skipping entity: (71, 73, 'LOCATION')
Skipping entity: (73, 75, 'LOCATION')
Skipping entity: (36, 44, 'LOCATION')
Skipping entity: (76, 78, 'LOCATION')
Skipping entity: (20, 22, 'LOCATION')
Skipping entity: (16, 24, 'LOCATION')
Skipping entity: (5, 7, 'LOCATION')
Skipping entity: (144, 146, 'LOCATION')
Skipping entity: (113, 121, 'LOCATION')
Skipping entity: (39, 41, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (67, 69, 'LOCATION')
Skipping entity: (95, 97, 'LOCATION')
Skipping entity: (21, 23, 'LOCATION')
Skipping entity: (6, 8, 'LOCATION')
Skipping entity: (80, 82, 'LOCATION')
Skipping entity: (116, 118, 'LOCATION')
Skipping entity: (70, 76, 'LOCATION')

 18%|█▊        | 2173/11849 [00:01<00:06, 1568.80it/s]

Skipping entity: (28, 30, 'LOCATION')
Skipping entity: (23, 25, 'LOCATION')
Skipping entity: (2, 4, 'LOCATION')
Skipping entity: (69, 77, 'LOCATION')
Skipping entity: (12, 14, 'LOCATION')
Skipping entity: (13, 21, 'LOCATION')
Skipping entity: (34, 36, 'LOCATION')
Skipping entity: (25, 27, 'LOCATION')
Skipping entity: (27, 32, 'LOCATION')
Skipping entity: (15, 17, 'LOCATION')
Skipping entity: (111, 113, 'LOCATION')
Skipping entity: (5, 7, 'LOCATION')
Skipping entity: (38, 40, 'LOCATION')
Skipping entity: (7, 19, 'LOCATION')
Skipping entity: (138, 148, 'LOCATION')
Skipping entity: (69, 77, 'LOCATION')
Skipping entity: (62, 69, 'LOCATION')
Skipping entity: (42, 44, 'LOCATION')
Skipping entity: (36, 37, 'LOCATION')
Skipping entity: (20, 26, 'LOCATION')
Skipping entity: (29, 31, 'LOCATION')
Skipping entity: (88, 96, 'LOCATION')
Skipping entity: (40, 42, 'LOCATION')
Skipping entity: (6, 7, 'LOCATION')
Skipping entity: (43, 47, 'LOCATION')
Skipping entity: (43, 47, 'LOCATION')
Skipping entity: (65, 73, 'LOCATION')
Skipping entity: (6, 8, 'LOCATION')
Skipping entity: (61, 66, 'LOCATION')
Skipping entity: (5, 10, 'LOCATION')
Skipping entity: (5, 12, 'LOCATION')
Skipping entity: (23, 25, 'LOCATION')
Skipping entity: (14, 16, 'LOCATION')
Skipping entity: (111, 119, 'LOCATION')
Skipping entity: (111, 119, 'LOCATION')
Skipping entity: (38, 40, 'LOCATION')
Skipping entity: (93, 95, 'LOCATION')
Skipping entity: (8, 10, 'LOCATION')
Skipping entity: (143, 151, 'LOCATION')
Skipping entity: (140, 142, 'LOCATION')
Skipping entity: (210, 212, 'LOCATION')
Skipping entity: (239, 241, 'LOCATION')
Skipping entity: (23, 25, 'LOCATION')
Skipping entity: (52, 54, 'LOCATION')
Skipping entity: (97, 101, 'LOCATION')
Skipping entity: (161, 163, 'LOCATION')
Skipping entity: (37, 39, 'LOCATION')
Skipping entity: (39, 43, 'LOCATION')
Skipping entity: (37, 39, 'LOCATION')
Skipping entity: (5, 7, 'LOCATION')
Skipping entity: (11, 16, 'LOCATION')
Skipping entity: (51, 53, 'LOCATION')
Skipping entity: (15, 17, 'LOCATION')
Skipping entity: (17, 25, 'LOCATION')

 21%|██        | 2484/11849 [00:01<00:06, 1490.26it/s]

Skipping entity: (40, 42, 'LOCATION')
Skipping entity: (205, 207, 'LOCATION')
Skipping entity: (37, 44, 'LOCATION')
Skipping entity: (15, 17, 'LOCATION')
Skipping entity: (53, 55, 'LOCATION')
Skipping entity: (71, 73, 'LOCATION')
Skipping entity: (52, 54, 'LOCATION')
Skipping entity: (124, 126, 'LOCATION')
Skipping entity: (31, 36, 'LOCATION')
Skipping entity: (77, 79, 'LOCATION')
Skipping entity: (78, 80, 'LOCATION')
Skipping entity: (28, 30, 'LOCATION')
Skipping entity: (46, 48, 'LOCATION')
Skipping entity: (90, 100, 'LOCATION')
Skipping entity: (11, 21, 'LOCATION')
Skipping entity: (34, 36, 'LOCATION')
Skipping entity: (68, 78, 'LOCATION')
Skipping entity: (49, 51, 'LOCATION')
Skipping entity: (52, 59, 'LOCATION')
Skipping entity: (110, 120, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (160, 166, 'LOCATION')
Skipping entity: (124, 134, 'LOCATION')
Skipping entity: (10, 20, 'LOCATION')
Skipping entity: (68, 78, 'LOCATION')
Skipping entity: (10, 12, 'LOCATION')
Skipping entity: (90, 98, 'LOCATION')
Skipping entity: (160, 170, 'LOCATION')
Skipping entity: (6, 16, 'LOCATION')
Skipping entity: (16, 26, 'LOCATION')
Skipping entity: (0, 2, 'LOCATION')
Skipping entity: (94, 104, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (52, 56, 'LOCATION')
Skipping entity: (27, 37, 'LOCATION')
Skipping entity: (42, 44, 'LOCATION')
Skipping entity: (74, 84, 'LOCATION')
Skipping entity: (58, 68, 'LOCATION')
Skipping entity: (24, 34, 'LOCATION')
Skipping entity: (45, 55, 'LOCATION')
Skipping entity: (59, 61, 'LOCATION')
Skipping entity: (0, 2, 'LOCATION')

 25%|██▍       | 2914/11849 [00:01<00:04, 1799.88it/s]

Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (73, 83, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (48, 58, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (34, 44, 'LOCATION')
Skipping entity: (14, 24, 'LOCATION')
Skipping entity: (20, 30, 'LOCATION')
Skipping entity: (175, 185, 'LOCATION')
Skipping entity: (0, 2, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (49, 59, 'LOCATION')
Skipping entity: (20, 30, 'LOCATION')
Skipping entity: (62, 72, 'LOCATION')
Skipping entity: (28, 31, 'LOCATION')
Skipping entity: (31, 36, 'LOCATION')
Skipping entity: (34, 44, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (36, 46, 'LOCATION')
Skipping entity: (59, 65, 'LOCATION')
Skipping entity: (128, 134, 'LOCATION')
Skipping entity: (134, 140, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (86, 96, 'LOCATION')
Skipping entity: (67, 77, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (16, 26, 'LOCATION')
Skipping entity: (103, 113, 'LOCATION')
Skipping entity: (22, 24, 'LOCATION')
Skipping entity: (46, 56, 'LOCATION')
Skipping entity: (30, 40, 'LOCATION')
Skipping entity: (77, 85, 'LOCATION')
Skipping entity: (92, 98, 'LOCATION')
Skipping entity: (23, 25, 'LOCATION')

 28%|██▊       | 3296/11849 [00:02<00:04, 1772.85it/s]

Skipping entity: (16, 26, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (74, 84, 'LOCATION')
Skipping entity: (190, 195, 'LOCATION')
Skipping entity: (182, 188, 'LOCATION')
Skipping entity: (30, 36, 'LOCATION')
Skipping entity: (36, 42, 'LOCATION')
Skipping entity: (25, 31, 'LOCATION')
Skipping entity: (169, 179, 'LOCATION')
Skipping entity: (122, 127, 'LOCATION')
Skipping entity: (133, 141, 'LOCATION')
Skipping entity: (87, 98, 'LOCATION')
Skipping entity: (99, 103, 'LOCATION')
Skipping entity: (6, 14, 'LOCATION')
Skipping entity: (50, 56, 'LOCATION')
Skipping entity: (59, 67, 'LOCATION')
Skipping entity: (5, 8, 'LOCATION')
Skipping entity: (194, 200, 'LOCATION')
Skipping entity: (189, 194, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')
Skipping entity: (2, 10, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (207, 218, 'LOCATION')
Skipping entity: (218, 224, 'LOCATION')
Skipping entity: (19, 29, 'LOCATION')
Skipping entity: (99, 107, 'LOCATION')
Skipping entity: (45, 48, 'LOCATION')
Skipping entity: (85, 91, 'LOCATION')
Skipping entity: (72, 80, 'LOCATION')
Skipping entity: (147, 157, 'LOCATION')
Skipping entity: (86, 92, 'LOCATION')
Skipping entity: (72, 82, 'LOCATION')
Skipping entity: (60, 68, 'LOCATION')
Skipping entity: (79, 82, 'LOCATION')
Skipping entity: (177, 181, 'LOCATION')
Skipping entity: (38, 48, 'LOCATION')

 33%|███▎      | 3857/11849 [00:02<00:04, 1829.87it/s]

Skipping entity: (34, 36, 'LOCATION')
Skipping entity: (3, 13, 'LOCATION')
Skipping entity: (174, 177, 'LOCATION')
Skipping entity: (7, 9, 'LOCATION')
Skipping entity: (73, 75, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (6, 14, 'LOCATION')
Skipping entity: (8, 18, 'LOCATION')
Skipping entity: (32, 36, 'LOCATION')
Skipping entity: (10, 20, 'LOCATION')
Skipping entity: (8, 16, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (39, 47, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (60, 68, 'LOCATION')
Skipping entity: (49, 57, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (66, 74, 'LOCATION')
Skipping entity: (49, 57, 'LOCATION')
Skipping entity: (6, 14, 'LOCATION')
Skipping entity: (38, 40, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (2, 7, 'LOCATION')
Skipping entity: (6, 10, 'LOCATION')
Skipping entity: (86, 90, 'LOCATION')
Skipping entity: (14, 22, 'LOCATION')
Skipping entity: (25, 27, 'LOCATION')
Skipping entity: (83, 87, 'LOCATION')
Skipping entity: (75, 83, 'LOCATION')

 36%|███▌      | 4250/11849 [00:02<00:04, 1736.41it/s]

Skipping entity: (81, 88, 'LOCATION')
Skipping entity: (76, 81, 'LOCATION')
Skipping entity: (76, 81, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (86, 88, 'LOCATION')
Skipping entity: (28, 35, 'LOCATION')
Skipping entity: (136, 144, 'LOCATION')
Skipping entity: (90, 98, 'LOCATION')
Skipping entity: (43, 51, 'LOCATION')
Skipping entity: (133, 139, 'LOCATION')
Skipping entity: (47, 55, 'LOCATION')
Skipping entity: (55, 59, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (41, 49, 'LOCATION')
Skipping entity: (0, 4, 'LOCATION')
Skipping entity: (172, 180, 'LOCATION')
Skipping entity: (42, 50, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (4, 6, 'LOCATION')
Skipping entity: (54, 60, 'LOCATION')
Skipping entity: (66, 68, 'LOCATION')
Skipping entity: (187, 193, 'LOCATION')
Skipping entity: (193, 203, 'LOCATION')
Skipping entity: (124, 131, 'LOCATION')
Skipping entity: (25, 33, 'LOCATION')
Skipping entity: (50, 58, 'LOCATION')

 39%|███▉      | 4640/11849 [00:02<00:03, 1833.68it/s]

Skipping entity: (64, 70, 'LOCATION')
Skipping entity: (35, 43, 'LOCATION')
Skipping entity: (38, 40, 'LOCATION')
Skipping entity: (33, 41, 'LOCATION')
Skipping entity: (6, 14, 'LOCATION')
Skipping entity: (10, 18, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (42, 50, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (78, 80, 'LOCATION')
Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (17, 25, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (60, 67, 'LOCATION')
Skipping entity: (44, 51, 'LOCATION')
Skipping entity: (26, 32, 'LOCATION')
Skipping entity: (245, 252, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (5, 10, 'LOCATION')
Skipping entity: (109, 111, 'LOCATION')
Skipping entity: (172, 177, 'LOCATION')
Skipping entity: (57, 59, 'LOCATION')
Skipping entity: (28, 34, 'LOCATION')
Skipping entity: (21, 28, 'LOCATION')
Skipping entity: (35, 42, 'LOCATION')
Skipping entity: (122, 124, 'LOCATION')
Skipping entity: (61, 63, 'LOCATION')
Skipping entity: (22, 23, 'LOCATION')

 44%|████▍     | 5267/11849 [00:03<00:03, 1997.82it/s]

Skipping entity: (4, 5, 'LOCATION')
Skipping entity: (39, 41, 'LOCATION')
Skipping entity: (34, 43, 'LOCATION')
Skipping entity: (27, 34, 'LOCATION')
Skipping entity: (21, 26, 'LOCATION')
Skipping entity: (71, 76, 'LOCATION')
Skipping entity: (35, 42, 'LOCATION')
Skipping entity: (67, 73, 'LOCATION')
Skipping entity: (118, 125, 'LOCATION')
Skipping entity: (60, 65, 'LOCATION')
Skipping entity: (14, 19, 'LOCATION')
Skipping entity: (93, 99, 'LOCATION')
Skipping entity: (39, 45, 'LOCATION')
Skipping entity: (1, 3, 'LOCATION')
Skipping entity: (92, 94, 'LOCATION')
Skipping entity: (1, 8, 'LOCATION')
Skipping entity: (68, 73, 'LOCATION')
Skipping entity: (45, 51, 'LOCATION')
Skipping entity: (98, 105, 'LOCATION')
Skipping entity: (50, 52, 'LOCATION')
Skipping entity: (22, 29, 'LOCATION')
Skipping entity: (70, 77, 'LOCATION')
Skipping entity: (86, 93, 'LOCATION')
Skipping entity: (93, 100, 'LOCATION')

 50%|████▉     | 5922/11849 [00:03<00:02, 2115.80it/s]

Skipping entity: (0, 10, 'LOCATION')
Skipping entity: (0, 1, 'LOCATION')
Skipping entity: (101, 111, 'LOCATION')
Skipping entity: (111, 120, 'LOCATION')
Skipping entity: (65, 67, 'LOCATION')
Skipping entity: (98, 104, 'LOCATION')
Skipping entity: (16, 21, 'LOCATION')
Skipping entity: (21, 29, 'LOCATION')
Skipping entity: (28, 31, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (58, 65, 'LOCATION')
Skipping entity: (37, 45, 'LOCATION')
Skipping entity: (15, 18, 'LOCATION')
Skipping entity: (52, 60, 'LOCATION')
Skipping entity: (16, 19, 'LOCATION')
Skipping entity: (103, 110, 'LOCATION')
Skipping entity: (97, 103, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (32, 36, 'LOCATION')
Skipping entity: (80, 87, 'LOCATION')
Skipping entity: (63, 66, 'LOCATION')
Skipping entity: (57, 64, 'LOCATION')
Skipping entity: (41, 49, 'LOCATION')
Skipping entity: (41, 49, 'LOCATION')
Skipping entity: (54, 59, 'LOCATION')
Skipping entity: (46, 54, 'LOCATION')
Skipping entity: (126, 133, 'LOCATION')
Skipping entity: (110, 118, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (64, 72, 'LOCATION')
Skipping entity: (69, 77, 'LOCATION')
Skipping entity: (13, 15, 'LOCATION')
Skipping entity: (69, 76, 'LOCATION')
Skipping entity: (31, 39, 'LOCATION')
Skipping entity: (31, 39, 'LOCATION')
Skipping entity: (117, 125, 'LOCATION')
Skipping entity: (37, 45, 'LOCATION')
Skipping entity: (63, 70, 'LOCATION')
Skipping entity: (128, 135, 'LOCATION')
Skipping entity: (75, 83, 'LOCATION')
Skipping entity: (64, 70, 'LOCATION')
Skipping entity: (3, 10, 'LOCATION')
Skipping entity: (95, 103, 'LOCATION')
Skipping entity: (60, 66, 'LOCATION')
Skipping entity: (41, 44, 'LOCATION')
Skipping entity: (115, 121, 'LOCATION')
Skipping entity: (218, 224, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (42, 50, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (82, 88, 'LOCATION')
Skipping entity: (47, 55, 'LOCATION')
Skipping entity: (52, 59, 'LOCATION')
Skipping entity: (12, 21, 'LOCATION')
Skipping entity: (0, 12, 'LOCATION')
Skipping entity: (201, 209, 'LOCATION')
Skipping entity: (71, 80, 'LOCATION')
Skipping entity: (80, 88, 'LOCATION')
Skipping entity: (67, 75, 'LOCATION')
Skipping entity: (46, 54, 'LOCATION')
Skipping entity: (0, 3, 'LOCATION')
Skipping entity: (45, 53, 'LOCATION')
Skipping entity: (26, 33, 'LOCATION')
Skipping entity: (26, 33, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')

 54%|█████▍    | 6427/11849 [00:03<00:02, 2303.42it/s]

Skipping entity: (13, 20, 'LOCATION')
Skipping entity: (74, 81, 'LOCATION')
Skipping entity: (72, 79, 'LOCATION')
Skipping entity: (12, 19, 'LOCATION')
Skipping entity: (15, 22, 'LOCATION')
Skipping entity: (56, 63, 'LOCATION')
Skipping entity: (11, 18, 'LOCATION')
Skipping entity: (65, 72, 'LOCATION')
Skipping entity: (43, 50, 'LOCATION')
Skipping entity: (41, 48, 'LOCATION')
Skipping entity: (31, 41, 'LOCATION')
Skipping entity: (18, 25, 'LOCATION')
Skipping entity: (79, 86, 'LOCATION')
Skipping entity: (56, 63, 'LOCATION')
Skipping entity: (18, 25, 'LOCATION')
Skipping entity: (54, 61, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (24, 31, 'LOCATION')
Skipping entity: (8, 15, 'LOCATION')
Skipping entity: (26, 33, 'LOCATION')
Skipping entity: (13, 20, 'LOCATION')
Skipping entity: (13, 20, 'LOCATION')
Skipping entity: (11, 18, 'LOCATION')
Skipping entity: (7, 14, 'LOCATION')
Skipping entity: (62, 69, 'LOCATION')
Skipping entity: (15, 20, 'LOCATION')
Skipping entity: (12, 19, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (7, 14, 'LOCATION')
Skipping entity: (25, 32, 'LOCATION')
Skipping entity: (19, 25, 'LOCATION')
Skipping entity: (56, 66, 'LOCATION')
Skipping entity: (3, 10, 'LOCATION')
Skipping entity: (71, 78, 'LOCATION')
Skipping entity: (9, 16, 'LOCATION')
Skipping entity: (11, 18, 'LOCATION')
Skipping entity: (49, 56, 'LOCATION')
Skipping entity: (23, 30, 'LOCATION')
Skipping entity: (14, 16, 'LOCATION')
Skipping entity: (54, 61, 'LOCATION')

 58%|█████▊    | 6924/11849 [00:03<00:02, 2404.30it/s]

Skipping entity: (39, 46, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (28, 35, 'LOCATION')
Skipping entity: (8, 15, 'LOCATION')
Skipping entity: (8, 15, 'LOCATION')
Skipping entity: (69, 76, 'LOCATION')
Skipping entity: (63, 69, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (42, 46, 'LOCATION')
Skipping entity: (54, 61, 'LOCATION')
Skipping entity: (80, 84, 'LOCATION')
Skipping entity: (23, 27, 'LOCATION')
Skipping entity: (74, 78, 'LOCATION')
Skipping entity: (13, 17, 'LOCATION')
Skipping entity: (17, 25, 'LOCATION')
Skipping entity: (0, 3, 'LOCATION')
Skipping entity: (45, 49, 'LOCATION')
Skipping entity: (17, 23, 'LOCATION')
Skipping entity: (19, 25, 'LOCATION')
Skipping entity: (69, 73, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (20, 24, 'LOCATION')
Skipping entity: (15, 23, 'LOCATION')
Skipping entity: (23, 30, 'LOCATION')
Skipping entity: (20, 28, 'LOCATION')
Skipping entity: (11, 16, 'LOCATION')
Skipping entity: (71, 79, 'LOCATION')
Skipping entity: (79, 86, 'LOCATION')
Skipping entity: (62, 66, 'LOCATION')
Skipping entity: (30, 32, 'LOCATION')
Skipping entity: (11, 18, 'LOCATION')
Skipping entity: (42, 48, 'LOCATION')
Skipping entity: (25, 33, 'LOCATION')
Skipping entity: (35, 42, 'LOCATION')
Skipping entity: (91, 98, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (20, 24, 'LOCATION')

 65%|██████▌   | 7737/11849 [00:04<00:01, 2607.01it/s]

Skipping entity: (19, 23, 'LOCATION')
Skipping entity: (63, 67, 'LOCATION')
Skipping entity: (10, 13, 'LOCATION')
Skipping entity: (61, 69, 'LOCATION')
Skipping entity: (69, 76, 'LOCATION')
Skipping entity: (13, 19, 'LOCATION')
Skipping entity: (12, 18, 'LOCATION')
Skipping entity: (69, 76, 'LOCATION')
Skipping entity: (76, 83, 'LOCATION')
Skipping entity: (7, 11, 'LOCATION')
Skipping entity: (11, 16, 'LOCATION')
Skipping entity: (67, 73, 'LOCATION')
Skipping entity: (55, 60, 'LOCATION')
Skipping entity: (17, 22, 'LOCATION')
Skipping entity: (2, 7, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (52, 61, 'LOCATION')
Skipping entity: (45, 52, 'LOCATION')
Skipping entity: (14, 19, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (27, 32, 'LOCATION')
Skipping entity: (105, 110, 'LOCATION')
Skipping entity: (63, 68, 'LOCATION')
Skipping entity: (12, 17, 'LOCATION')
Skipping entity: (41, 46, 'LOCATION')
Skipping entity: (3, 7, 'LOCATION')
Skipping entity: (56, 61, 'LOCATION')
Skipping entity: (63, 68, 'LOCATION')
Skipping entity: (39, 44, 'LOCATION')
Skipping entity: (9, 14, 'LOCATION')
Skipping entity: (14, 20, 'LOCATION')
Skipping entity: (10, 15, 'LOCATION')
Skipping entity: (35, 40, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (16, 21, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (14, 19, 'LOCATION')
Skipping entity: (23, 28, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (14, 20, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (3, 6, 'LOCATION')
Skipping entity: (22, 25, 'LOCATION')
Skipping entity: (10, 12, 'LOCATION')
Skipping entity: (58, 60, 'LOCATION')
Skipping entity: (26, 31, 'LOCATION')
Skipping entity: (20, 25, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (19, 24, 'LOCATION')
Skipping entity: (25, 30, 'LOCATION')
Skipping entity: (63, 68, 'LOCATION')
Skipping entity: (12, 17, 'LOCATION')

 70%|███████   | 8340/11849 [00:04<00:01, 2798.87it/s]

Skipping entity: (26, 31, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (10, 13, 'LOCATION')
Skipping entity: (13, 18, 'LOCATION')
Skipping entity: (37, 42, 'LOCATION')
Skipping entity: (55, 59, 'LOCATION')
Skipping entity: (61, 66, 'LOCATION')
Skipping entity: (42, 47, 'LOCATION')
Skipping entity: (55, 58, 'LOCATION')
Skipping entity: (58, 63, 'LOCATION')
Skipping entity: (74, 79, 'LOCATION')
Skipping entity: (0, 5, 'LOCATION')
Skipping entity: (6, 13, 'LOCATION')
Skipping entity: (8, 13, 'LOCATION')
Skipping entity: (15, 20, 'LOCATION')
Skipping entity: (93, 100, 'LOCATION')
Skipping entity: (11, 13, 'LOCATION')
Skipping entity: (7, 12, 'LOCATION')
Skipping entity: (10, 13, 'LOCATION')
Skipping entity: (73, 80, 'LOCATION')
Skipping entity: (80, 82, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (92, 94, 'LOCATION')
Skipping entity: (94, 96, 'LOCATION')
Skipping entity: (96, 98, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (30, 38, 'LOCATION')
Skipping entity: (38, 41, 'LOCATION')
Skipping entity: (19, 28, 'LOCATION')
Skipping entity: (9, 12, 'LOCATION')
Skipping entity: (4, 6, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (11, 14, 'LOCATION')
Skipping entity: (29, 36, 'LOCATION')
Skipping entity: (1, 4, 'LOCATION')
Skipping entity: (8, 10, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (10, 12, 'LOCATION')
Skipping entity: (44, 56, 'LOCATION')
Skipping entity: (10, 12, 'LOCATION')
Skipping entity: (55, 62, 'LOCATION')
Skipping entity: (6, 9, 'LOCATION')
Skipping entity: (10, 13, 'LOCATION')
Skipping entity: (73, 75, 'LOCATION')
Skipping entity: (21, 24, 'LOCATION')
Skipping entity: (3, 6, 'LOCATION')

 75%|███████▌  | 8890/11849 [00:04<00:01, 2651.97it/s]

Skipping entity: (21, 31, 'LOCATION')
Skipping entity: (3, 6, 'LOCATION')
Skipping entity: (3, 6, 'LOCATION')
Skipping entity: (9, 12, 'LOCATION')
Skipping entity: (47, 54, 'LOCATION')
Skipping entity: (7, 10, 'LOCATION')
Skipping entity: (14, 17, 'LOCATION')
Skipping entity: (24, 31, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (4, 11, 'LOCATION')
Skipping entity: (5, 8, 'LOCATION')
Skipping entity: (9, 11, 'LOCATION')
Skipping entity: (20, 30, 'LOCATION')
Skipping entity: (39, 41, 'LOCATION')
Skipping entity: (38, 40, 'LOCATION')
Skipping entity: (7, 9, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (18, 21, 'LOCATION')
Skipping entity: (21, 23, 'LOCATION')
Skipping entity: (65, 71, 'LOCATION')
Skipping entity: (71, 74, 'LOCATION')
Skipping entity: (2, 10, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (101, 110, 'LOCATION')
Skipping entity: (108, 116, 'LOCATION')
Skipping entity: (2, 10, 'LOCATION')
Skipping entity: (6, 14, 'LOCATION')
Skipping entity: (102, 113, 'LOCATION')
Skipping entity: (113, 121, 'LOCATION')
Skipping entity: (4, 9, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')

 82%|████████▏ | 9711/11849 [00:04<00:00, 2654.87it/s]

Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (13, 21, 'LOCATION')
Skipping entity: (73, 75, 'LOCATION')
Skipping entity: (50, 55, 'LOCATION')
Skipping entity: (54, 56, 'LOCATION')
Skipping entity: (20, 29, 'LOCATION')
Skipping entity: (33, 39, 'LOCATION')
Skipping entity: (29, 31, 'LOCATION')
Skipping entity: (48, 57, 'LOCATION')
Skipping entity: (41, 48, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (69, 76, 'LOCATION')
Skipping entity: (34, 40, 'LOCATION')
Skipping entity: (75, 81, 'LOCATION')
Skipping entity: (38, 45, 'LOCATION')
Skipping entity: (0, 7, 'LOCATION')
Skipping entity: (40, 49, 'LOCATION')
Skipping entity: (35, 40, 'LOCATION')
Skipping entity: (26, 28, 'LOCATION')
Skipping entity: (0, 9, 'LOCATION')
Skipping entity: (66, 73, 'LOCATION')
Skipping entity: (58, 62, 'LOCATION')
Skipping entity: (28, 30, 'LOCATION')
Skipping entity: (10, 16, 'LOCATION')
Skipping entity: (17, 23, 'LOCATION')
Skipping entity: (15, 20, 'LOCATION')
Skipping entity: (72, 79, 'LOCATION')
Skipping entity: (17, 22, 'LOCATION')

 87%|████████▋ | 10307/11849 [00:05<00:00, 2806.51it/s]

Skipping entity: (27, 34, 'LOCATION')
Skipping entity: (52, 59, 'LOCATION')
Skipping entity: (41, 43, 'LOCATION')
Skipping entity: (27, 29, 'LOCATION')
Skipping entity: (33, 36, 'LOCATION')
Skipping entity: (0, 9, 'LOCATION')
Skipping entity: (0, 2, 'LOCATION')
Skipping entity: (15, 16, 'LOCATION')
Skipping entity: (23, 27, 'LOCATION')
Skipping entity: (0, 2, 'LOCATION')
Skipping entity: (11, 16, 'LOCATION')
Skipping entity: (48, 54, 'LOCATION')
Skipping entity: (9, 10, 'LOCATION')
Skipping entity: (30, 32, 'LOCATION')
Skipping entity: (55, 60, 'LOCATION')
Skipping entity: (9, 13, 'LOCATION')
Skipping entity: (24, 31, 'LOCATION')
Skipping entity: (57, 59, 'LOCATION')
Skipping entity: (22, 24, 'LOCATION')
Skipping entity: (3, 14, 'LOCATION')
Skipping entity: (39, 45, 'LOCATION')
Skipping entity: (4, 10, 'LOCATION')
Skipping entity: (16, 22, 'LOCATION')
Skipping entity: (34, 40, 'LOCATION')
Skipping entity: (12, 18, 'LOCATION')
Skipping entity: (38, 44, 'LOCATION')
Skipping entity: (28, 34, 'LOCATION')
Skipping entity: (18, 24, 'LOCATION')
Skipping entity: (56, 62, 'LOCATION')

 94%|█████████▍| 11170/11849 [00:05<00:00, 2854.79it/s]

Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (43, 49, 'LOCATION')
Skipping entity: (28, 34, 'LOCATION')
Skipping entity: (46, 52, 'LOCATION')
Skipping entity: (42, 48, 'LOCATION')
Skipping entity: (67, 73, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (7, 11, 'LOCATION')
Skipping entity: (55, 57, 'LOCATION')
Skipping entity: (27, 30, 'LOCATION')
Skipping entity: (3, 8, 'LOCATION')
Skipping entity: (49, 55, 'LOCATION')
Skipping entity: (42, 46, 'LOCATION')
Skipping entity: (71, 77, 'LOCATION')
Skipping entity: (95, 105, 'LOCATION')
Skipping entity: (42, 48, 'LOCATION')
Skipping entity: (24, 30, 'LOCATION')
Skipping entity: (57, 63, 'LOCATION')
Skipping entity: (5, 8, 'LOCATION')
Skipping entity: (59, 65, 'LOCATION')
Skipping entity: (90, 96, 'LOCATION')
Skipping entity: (16, 22, 'LOCATION')
Skipping entity: (58, 65, 'LOCATION')
Skipping entity: (43, 49, 'LOCATION')
Skipping entity: (20, 22, 'LOCATION')
Skipping entity: (21, 27, 'LOCATION')
Skipping entity: (12, 18, 'LOCATION')
Skipping entity: (59, 65, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (43, 45, 'LOCATION')
Skipping entity: (11, 17, 'LOCATION')
Skipping entity: (6, 12, 'LOCATION')
Skipping entity: (7, 13, 'LOCATION')
Skipping entity: (13, 18, 'LOCATION')

 99%|█████████▉| 11737/11849 [00:05<00:00, 2667.88it/s]

Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (104, 106, 'LOCATION')
Skipping entity: (7, 11, 'LOCATION')
Skipping entity: (86, 92, 'LOCATION')
Skipping entity: (43, 48, 'LOCATION')
Skipping entity: (54, 56, 'LOCATION')
Skipping entity: (56, 58, 'LOCATION')
Skipping entity: (9, 19, 'LOCATION')
Skipping entity: (3, 11, 'LOCATION')
Skipping entity: (6, 8, 'LOCATION')
Skipping entity: (0, 8, 'LOCATION')
Skipping entity: (111, 117, 'LOCATION')
Skipping entity: (3, 7, 'LOCATION')
Skipping entity: (48, 54, 'LOCATION')
Skipping entity: (65, 71, 'LOCATION')
Skipping entity: (58, 64, 'LOCATION')
Skipping entity: (25, 31, 'LOCATION')
Skipping entity: (96, 106, 'LOCATION')
Skipping entity: (44, 50, 'LOCATION')
Skipping entity: (57, 61, 'LOCATION')
Skipping entity: (101, 107, 'LOCATION')
Skipping entity: (12, 14, 'LOCATION')
Skipping entity: (43, 53, 'LOCATION')
Skipping entity: (30, 36, 'LOCATION')
Skipping entity: (45, 51, 'LOCATION')
Skipping entity: (0, 6, 'LOCATION')
Skipping entity: (65, 71, 'LOCATION')
Skipping entity: (9, 15, 'LOCATION')
Skipping entity: (3, 5, 'LOCATION')
Skipping entity: (3, 9, 'LOCATION')
Skipping entity: (90, 100, 'LOCATION')
Skipping entity: (13, 19, 'LOCATION')
Skipping entity: (19, 23, 'LOCATION')
Skipping entity: (102, 106, 'LOCATION')
Skipping entity: (7, 9, 'LOCATION')
Skipping entity: (47, 55, 'LOCATION')
Skipping entity: (11, 12, 'LOCATION')

100%|██████████| 11849/11849 [00:05<00:00, 2116.06it/s]

Skipping entity: (23, 27, 'LOCATION')
Skipping entity: (42, 44, 'LOCATION')
Skipping entity: (61, 67, 'LOCATION')
Skipping entity: (19, 25, 'LOCATION')
Skipping entity: (20, 26, 'LOCATION')
Skipping entity: (24, 30, 'LOCATION')

In [43]:
!python -m spacy init fill-config base_config.cfg config.cfg

✔ Auto-filled config with all values
✔ Saved config
config.cfg
You can now add your data and train your pipeline:
python -m spacy train config.cfg --paths.train ./train.spacy --paths.dev ./dev.spacy

In [44]:
!python -m spacy train config.cfg --output ./ --paths.train ./train.spacy --paths.dev ./train.spacy

ℹ Saving to output directory: .
ℹ Using CPU

=========================== Initializing pipeline ===========================
✔ Initialized pipeline

============================= Training pipeline =============================
ℹ Pipeline: ['tok2vec', 'ner']
ℹ Initial learn rate: 0.001
E    #       LOSS TOK2VEC  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE
---  ------  ------------  --------  ------  ------  ------  ------
  0       0          0.00     35.33    0.58    0.55    0.62    0.01
  0     200          6.24   1416.50   81.74   80.19   83.36    0.82
  0     400          7.81    969.22   84.46   80.73   88.55    0.84
  0     600         10.33   1150.86   83.84   85.79   81.98    0.84
  0     800         17.33   1377.70   85.93   82.43   89.75    0.86
  0    1000         23.73   1650.81   86.00   86.33   85.68    0.86
  0    1200         31.82   2023.14   86.57   85.64   87.51    0.87
  1    1400         34.48   2348.60   87.47   86.33   88.64    0.87
  1    1600         43.90   2540.41   88.24   84.62   92.18    0.88
  1    1800         46.00   3042.84   88.35   88.87   87.85    0.88
  2    2000         45.73   3480.68   89.64   89.19   90.11    0.90
  2    2200         50.49   4045.84   90.81   86.80   95.21    0.91
  3    2400         60.69   4062.15   91.68   87.96   95.74    0.92
  4    2600         58.61   4036.25   92.91   91.04   94.85    0.93
  5    2800         56.81   3836.66   93.30   91.00   95.72    0.93
  5    3000         66.59   3410.49   93.53   94.17   92.89    0.94
  6    3200         63.64   3115.58   94.71   92.75   96.75    0.95
  7    3400         57.63   2926.04   94.79   94.76   94.82    0.95
  8    3600         63.96   2716.07   95.61   94.38   96.88    0.96
  9    3800         65.25   2536.26   95.66   93.71   97.70    0.96
  9    4000         70.24   2318.58   96.20   94.44   98.03    0.96
✔ Saved pipeline to output directory
model-last

In [45]:
 nlp_ner = spacy.load("model-best")

In [46]:
doc = nlp_ner("flash flood strike maryland city sunday wash street toss car like bath toy")
colors = {"LOCATION": "#F67DE3"}
options = {"colors": colors}

spacy.displacy.render(doc, style="ent", options= options, jupyter=True)

In [48]:
train['text'].iloc[8]

'One man is still missing after flash flooding tore down historic Main Street in Ellicott City Maryland over the weekend'

In [49]:
doc = nlp_ner("One man is still missing after flash flooding tore down historic Main Street in Ellicott City, Maryland over the weekend")
colors = {"LOCATION": "#F67DE3"}
options = {"colors": colors}

spacy.displacy.render(doc, style="ent", options= options, jupyter=True)

In [50]:

test.head()

                 tweet_id                                               text
0  ID_1001154804658286592  What is happening to the infrastructure in New...
1  ID_1001155505459486720  SOLDER MISSING IN FLOOD PRAY FOR EDDISON HERMO...
2  ID_1001155756371136512  RT TIME Police searching for missing person af...
3  ID_1001159445194399744  Flash Flood Tears Through Maryland Town For Se...
4  ID_1001164907587538944  Ellicott City FLOODING Pictures Maryland Gover...

In [51]:
import spacy
import pandas as pd
# Load the pre-trained spaCy model for location recognition
nlp_ner1 = spacy.load('model-best')

# Function to extract locations from text using the spaCy NER model
def extract_locations(text):
    doc = nlp_ner(text)
    locations = [ent.text for ent in doc.ents if ent.label_ == "LOCATION"]
    # Return the locations as a string joined by commas or an empty string if none found
    return ', '.join(locations) if locations else None


# Apply the location extraction function to the text column
test['locations'] = test['text'].apply(extract_locations)

# Save the updated test data with the new locations column
test[['tweet_id', 'locations']].to_csv('submit11_test_data.csv', index=False)

# Preview the updated test data
test[['tweet_id', 'locations']].head()

                 tweet_id                   locations
0  ID_1001154804658286592  New, England, New, Orleans
1  ID_1001155505459486720    ELLICOTT, CITY, MARYLAND
2  ID_1001155756371136512    Ellicott, City, Maryland
3  ID_1001159445194399744    Maryland, Ellicott, City
4  ID_1001164907587538944    Ellicott, City, Maryland